//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hyk_WebApi.Models.Enityt_Framework_File
{
    using System;
    using System.Collections.Generic;
    
    public partial class RATING
    {
        public int ID_ { get; set; }
        public System.DateTime DATE_ { get; set; }
        public int STARS_ { get; set; }
        public int RATER_ID_ { get; set; }
        public int RATEE_ID_ { get; set; }
        public string COMMENT_ { get; set; }
    }
}
