//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hyk_WebApi.Models.Enityt_Framework_File
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRIP_MATCH
    {
        public int ID_ { get; set; }
        public int PASSANGERS_TRIP_ID_ { get; set; }
        public int DRIVERS_TRIP_ID_ { get; set; }
        public bool ACCEPTED_ { get; set; }
    
        public virtual TRIP TRIP { get; set; }
        public virtual TRIP TRIP1 { get; set; }
    }
}
