//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hyk_WebApi.Models.Enityt_Framework_File
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.CARDs = new HashSet<CARD>();
        }
    
        public int ID_ { get; set; }
        public string FIRSTNAME_ { get; set; }
        public string LASTNAME_ { get; set; }
        public string EMAIL_ { get; set; }
        public string CONTACT_NUMBER_ { get; set; }
        public string PICTURE_ { get; set; }
        public int AVERAGE_RATING_ { get; set; }
        public System.DateTime DATE_REGISTERED_ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARD> CARDs { get; set; }
        public virtual PASSENGER PASSENGER { get; set; }
        public virtual DRIVER DRIVER { get; set; }
        public virtual PREFERENCE PREFERENCE { get; set; }
    }
}
